### ISSUE TITLE
Testnet mode is generateing mainnet addresses for orders

### ISSUE THREAD

**Issue by h0jeZvgoxFepBQ2C** [MyceliumGear/straight#29]
Looks like testnet is not working correctly, order addresses are generated on main net, even if testmode is set:

```ruby
    gateway = Straight::Gateway.new
    gateway.test_pubkey                 = "tpubD8v67BgSqFQzKPVxN6Bs5xUeWX9Pu4geg9KkNUQ8hPPZeaSszkdBGnDwsDWXCsxt4msPaWcHJBYuRSwjJAF2fZeh1ZcEyH5J1ccLv7KKV4z"
    gateway.confirmations_required = 0
    gateway.order_class            = 'Straight::Order'
    gateway.default_currency       = 'BTC'
    gateway.name                   = 'Bitcoin Payments'
    gateway.test_mode              = true
    order = gateway.new_order(amount: 1, keychain_id: 1)
    puts order.address
    => 1K8dhDNTGNMBwCL2hapsu1hzCHDLrvR3eM
    # which is not a testnet address
```

I think this is related to this: https://github.com/oleganza/btcruby/issues/20

**Comment by h0jeZvgoxFepBQ2C** [comment]
This issue was fixed 1,5 years ago in btcruby (commit: 3006f458202d31ae1e84ac56c0d5d33fb993d801)...

**Comment by h0jeZvgoxFepBQ2C** [comment]
Damn, I just found out where the problem is... btcruby latest release is 2,5 years old (1.6) - even if there is still development ongoing... Opened a issue there...

**Comment by AlexanderPavlenko** [comment]
Hello! In case this is still an issue, feel free to submit it to https://github.com/mycelium-com/gear-engine/issues
