### ISSUE TITLE
Active development?

### ISSUE THREAD

**Issue by h0jeZvgoxFepBQ2C** [MyceliumGear/straight#34]
Hi @snitko @alekstkach @AlexanderPavlenko 

First of all: thank you very much for your great work with straight and the corresponding other projects!

I just wanted to ask if you are still actively maintaining this project?
If you need some help, I would be really happy to contribute somehow or if you need another additional maintainer?

**Comment by snitko** [comment]
To my knowledge no, it's not actively maintained.

**Comment by h0jeZvgoxFepBQ2C** [comment]
Hm sad.. :/

May I ask why? Straight / Mycelium Gear is a really cool library?!
Do you think there is any possibility to help to get the development running again?

**Comment by snitko** [comment]
I left Mycelium more than a year ago and moved on to other projects. I know Gear is still working as a service though, but have no idea what's going on inside.

**Comment by h0jeZvgoxFepBQ2C** [comment]
Ah ok, sorry to bother you - just looked on the contributor site and you are the first mentioned committer :)

Could you maybe tell me who is in charge of these things at the moment maybe?

**Comment by snitko** [comment]
As far as I know, @AlexanderPavlenko is still working there.

**Comment by h0jeZvgoxFepBQ2C** [comment]
@AlexanderPavlenko I think I will fork this repository and build up on it, if you don't mind and are not looking for a helping hand?

**Comment by AlexanderPavlenko** [comment]
Hello! In case this is still an issue, feel free to submit it to https://github.com/mycelium-com/gear-engine/issues
